<?php
abstract class Person
{
    public $surname;
    public $gradeBook;

    function __construct($surname, $gradeBook)
    {
        $this->surname = $surname;
        $this->gradeBook = $gradeBook;
    }
    function print(){}
}

class Student extends Person
{
    public $course;
    function __construct($surname, $gradeBook, $course)
    {
        parent::__construct($surname, $gradeBook);
        $this->course=$course;
    }
    function print()
    {
        parent::print(); // TODO: Change the autogenerated stub
        echo "Student - $this->surname, Course - $this->course, Gradebook - $this->gradeBook</br>";
    }
}
class Aspirant extends Person
{
    public $dissertation;
    public function __construct($surname, $gradeBook, $dissertation)
    {
        parent::__construct($surname, $gradeBook);
        $this->dissertation = $dissertation;
    }
    function print()
    {
        parent::print(); // TODO: Change the autogenerated stub
        echo "Aspirant - $this->surname, Gradebook - $this->gradeBook, Dissertation - $this->dissertation</br>";
    }
}

    $student1 = new Student ("Jerry", 22, 3);
    $student1->print();
    $aspirant1 = new Aspirant("Tom", 11, 2);
    $aspirant1->print();
