<h3>Student</h3>
<form method="POST">
    <p>Surname: <input type="text", name="asSurname"></p>
    <p>GradeBook: <input type="number", name="asGradeBook"></p>
    <p>Dissertation: <input type="text", name="dissertation"></p>
    <input type="submit", value="Accept">
    <input type="button" onclick="history.go(-1);" value="Back to the Menu">
</form>
<?php
if(isset($_POST['asSurname']) && isset($_POST['asGradeBook']) && isset($_POST['dissertation']))
{
    $asSurname=htmlentities($_POST['asSurname']);
    $asGradeBook=htmlentities($_POST['asGradeBook']);
    $dissertation=htmlentities($_POST['dissertation']);
    if(preg_match('/^[A-Za-z]*$/', $asSurname) && is_numeric($asGradeBook) && preg_match('/^[A-Za-z]*$/', $dissertation))
    {
        abstract class Person
        {
            public $asSurname;
            public $asGradeBook;

            function __construct($asSurname, $asGradeBook)
            {
                $this->asSurname = $asSurname;
                $this->asGradeBook = $asGradeBook;
            }
            function print(){}
        }
        class Aspirant extends Person
        {
            public $dissertation;
            public function __construct($asSurname, $asGradeBook, $dissertation)
            {
                parent::__construct($asSurname, $asGradeBook);
                $this->dissertation = $dissertation;
            }
            function print()
            {
                parent::print(); // TODO: Change the autogenerated stub
                echo "Aspirant - $this->asSurname, Gradebook - $this->asGradeBook, Dissertation - $this->dissertation</br>";
            }
        }
        $aspirant = new Aspirant($asSurname, $asGradeBook, $dissertation);
        $aspirant->print();
    }
    else
    {
        echo "wrong symbols pls try again";
    }
}
